### ISSUE TITLE
Ordering

### ISSUE THREAD

**Issue by CHEWX** [ryanburgess/2018-conferences#28]
Hey,

I've noticed it's hard to keep event dates in order, well impossible without having tests.

As such, I think a restructure to `whenFrom` and `whenTo` with a date format of `ddmmyyyy`.

This can then be ordered easily, and also output as a human readable format. Rather that it currently being inputted as human readable, but as such impossible to sort and change date format.

Thoughts on this?

Happy to go through and change them and do a PR with a sort. Certainly don't want to do a PR and it not get accepted, ha ha.

Thanks,
Tom

**Comment by ryanburgess** [comment]
That's a great idea! If you'd like to help, that'd be amazing! I'd accept the PR for sure :)

**Comment by ryanburgess** [comment]
Thanks for the the fix @CHEWX
